name: Keep Render Alive

on:
  schedule:
    # 매 5분마다 실행
    - cron: "*/5 * * * *"
    # 오프셋 실행: 매 10분마다 2분 후 (지터 보정)
    - cron: "2-59/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Ping Render /healthz with retries
        shell: bash
        run: |
          URL="https://interior-estimator-flask.onrender.com/healthz"
          echo "[keep-alive] $(date -u +"%Y-%m-%dT%H:%M:%SZ") -> $URL"
          for i in 1 2 3; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 15 "$URL" || true)
            echo "  attempt $i: HTTP $CODE"
            # 2xx 또는 3xx면 성공 처리 후 종료
            [[ "${CODE:0:1}" =~ [23] ]] && exit 0
            sleep 60
          done
          echo "  all attempts failed (likely waking)."
          # Render가 깨어나느라 실패했더라도 워크플로우 자체는 실패로 표시하지 않음
          exit 0
